backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'semantic-router/backend/**/*'
          - 'semantic-router/Dockerfile'
          - 'semantic-router/requirements.txt'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - docs/**/*

testing:
  - changed-files:
      - any-glob-to-any-file:
          - semantic-router/backend/tests/**/*
          - .github/workflows/test.yaml

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**/*

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - semantic-router/backend/requirements.txt
          - semantic-router/backend/requirements_test.txt
          - .github/dependabot.yml
